routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HorarioController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource("horariosprueba" , HorarioController::class);

app/Models/Horario_Atencion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Horario_Atencion extends Model
{
    use HasFactory;
    protected $table = "horario";
    protected $primarykey = "id";
    public $timestamps = false;
    protected $fillable = [

        "id",
        "hora_apertura",
        "hora_cierre",
        "dia_atencion",
        "test1_validation",
        "test2_validation",
        "test3_validation",
        "test4_validation",
        "cedula_test",
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/HorarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Horario_Atencion;
use Illuminate\Support\Facades\Validator;

class HorarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $horariosprueba = Horario_Atencion::all();
        return view ("TestHorarios.index", compact ("horariosprueba"));
       // return $horariosprueba;
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('TestHorarios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator :: make ($request->all(),[
            "dia_atencion" => "date_format:Y-m-d",
            "hora_cierre" => "required",
            "hora_apertura" => "required",
            "test1_validation" => "email",
            "test2_validation" => "alpha_num",
            "test3_validation" => "alpha",
            "test4_validation" => "integer",

        ]);

        if($v->fails())
        {

                return redirect () -> back () -> withErrors($v->errors())->withInput();

           }else {

            Horario_Atencion::create($request->all());
            return redirect()->route('horariosprueba.index')->with('success','Horario creado exitosamente!!');

           }

       

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Horario_Atencion $horariosprueba)
    {
        return view('TestHorarios.edit', compact ("horariosprueba"));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $horariosprueba = Horario_Atencion :: find ($id);
        $horariosprueba -> update ($request -> all());
        return redirect () -> route ("horariosprueba.index") -> with ("success","Horario modificado con exito");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $horariosprueba = Horario_Atencion :: find ($id);
        $horariosprueba -> delete ();
        return redirect () -> route ("horariosprueba.index") -> with ("success","Horario eliminado con exito");

    }
}

resources/views/TestHorarios/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Horario</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('horariosprueba.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('horariosprueba.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Dia de atencion:</strong>
                        <input type="date" name="dia_atencion" class="form-control"
                            placeholder="Ingresar el dia de su reserva" value="{{old("dia_atencion")}}" required>
                        @error( "dia_atencion")
                        <p>{{$message}}</p>
                        @enderror


                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora de apertura:</strong>
                        <input type="time" name="hora_apertura" class="form-control"
                            placeholder="Ingresar la hora inicial de su reserva"value="{{old("hora_apertura")}}" required>

                            @error( "hora_apertura")
                        <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora de cierre:</strong>
                        <input type="time" name="hora_cierre" class="form-control"
                            placeholder="Ingresar la hora final de su reserva"value="{{old("hora_cierre")}}" required>
                            @error( "hora_cierre")
                        <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>


                <div>
                    <div class="form-group">
                        <strong>Ingresar numero de telefono:</strong>
                        <input type="tel" name="cedula_test" class="form-control"
                        value="{{ old('cedula_test') }}" pattern="[+][0-5]{3}[0-9]{9}">
                        @error('cedula_test')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>


                <div>
                    <div class="form-group">
                        <strong>Prueba 1:</strong>
                        <input type="email" name="test1_validation" class="form-control"
                            placeholder="Testeo2"value="{{old("test1_validation")}}" required>
                            @error( "test1_validation")
                        <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Prueba 2:</strong>
                        <input type="text" name="test2_validation" class="form-control"
                            placeholder="Testeo 1"value="{{old("test2_validation")}}" minlength="4">
                            @error( "test2_validation")
                        <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Prueba 3:</strong>
                        <input type="text" name="test3_validation" class="form-control"
                            placeholder="Testeo 3"value="{{old("test2_validation")}}" maxlength="6">
                            @error( "test3_validation")
                        <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>


                <div>
                    <div class="form-group">
                        <strong>Prueba 4:</strong>
                        <input type="number" name="test4_validation" class="form-control"
                            placeholder="Testeo 4"value="{{old("test2_validation")}}" max="5">
                            @error( "test4_validation")
                        <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>

                

                <div class="col-xs-12 col-sm-12 col-md-12 text-center"> 
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/TestHorarios/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Horario de Atención</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horariosprueba.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('horariosprueba.update',$horariosprueba->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Día Atención:</strong>
                    <input type="date" name="dia_atencion" class="form-control" value="{{ $horariosprueba->dia_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Inicio Atención:</strong>
                    <input type="time" name="hora_apertura" class="form-control" value="{{ $horariosprueba->hora_apertura }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Fin Atención:</strong>
                    <input type="time" name="hora_cierre" class="form-control" value="{{ $horariosprueba->hora_cierre }}">
                </div>
            </div>


            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Cedula:</strong>
                    <input type="time" name="cedula_test" class="form-control" value="{{ $horariosprueba->cedula_test }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Test 1:</strong>
                    <input type="email" name="test1_validation" class="form-control" value="{{ $horariosprueba->test1_validation }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Test 2:</strong>
                    <input type="text" name="test2_validation" class="form-control" value="{{ $horariosprueba->test2_validation }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Test 3:</strong>
                    <input type="text" name="test3_validation" class="form-control" value="{{ $horariosprueba->test3_validation }}">
                </div>
            </div>


            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Test 4:</strong>
                    <input type="number" name="test4_validation" class="form-control" value="{{ $horariosprueba->test4_validation }}">
                </div>
            </div>

            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/TestHorarios/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE HORARIOS DE RESERVAS</h1>
        <div>
            <a class="btn btn-success" href="{{ route('horariosprueba.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Dia Atención</th>
                <th>Hora De Apertura</th>
                <th>Hora De Cierre</th>
                <th>Telefono</th>
                <th>Test 1</th>
                <th>Test 2</th>
                <th>Test 3</th>
                <th>Test 4</th>
                <th>Botones</th>
            </tr>
            @foreach ($horariosprueba as $horario)
                <tr>
                    <td>{{ $horario->id }}</td>
                    <td>{{ $horario->dia_atencion }}</td>
                    <td>{{ $horario->hora_apertura }}</td>
                    <td>{{ $horario->hora_cierre }}</td>
                    <td>{{$horario->cedula_test}}</td>
                    <td>{{ $horario->test1_validation }}</td>
                    <td>{{ $horario->test2_validation }}</td>
                    <td>{{ $horario->test3_validation }}</td>
                    <td>{{ $horario->test4_validation }}</td>

                    <td><a class="btn btn-primary" href="{{ route('horariosprueba.edit',$horario) }}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <form action="{{ route('horariosprueba.destroy',$horario->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>